services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_dev
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      # This variable will now be pulled from your .env file
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      # Persists your database data locally so it survives container restarts
      - ../.mssql_data:/var/opt/mssql
      # Common data folder for all tutorials
      - ../data:/container_data
      # maps prj folder to container
      - ../..:/workspaces:cached
    user: root
